<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($term, $order = 'asc', $limit = 20, $offset = 0)
    {
        $qb = $this->createQueryBuilder('article')
                   ->orderBy('article.title', $order);

        if ($term) {
            $qb->where('article.title LIKE ?1')
               ->setParameter(1, '%'.$term.'%');
        }

        return $this->paginate($qb, $limit, $offset);
    }
}
